mkdir -p "../../../target/compiledC/algorithms"
mkdir -p "../../../target/compiledC/tests"
mkdir -p "../../../target/compiledC/utils"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/algorithms/BellmanFordParallelV1.o" "./algorithms/BellmanFordParallelV1.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/algorithms/BellmanFordSerial.o" "./algorithms/BellmanFordSerial.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/algorithms/DijkstraSerial.o" "./algorithms/DijkstraSerial.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/algorithms/Graph.o" "./algorithms/Graph.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/tests/Main.o" "./tests/Main.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/tests/TestGraphGenerator.o" "./tests/TestGraphGenerator.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/utils/ArraysUtilities.o" "./utils/ArraysUtilities.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/utils/GraphGenerator.o" "./utils/GraphGenerator.c"
gcc -fopenmp -o "Shortest Path" "../../../target/compiledC/algorithms/BellmanFordParallelV1.o" "../../../target/compiledC/algorithms/BellmanFordSerial.o" "../../../target/compiledC/algorithms/DijkstraSerial.o" "../../../target/compiledC/algorithms/Graph.o" "../../../target/compiledC/tests/Main.o" "../../../target/compiledC/tests/TestGraphGenerator.o" "../../../target/compiledC/utils/ArraysUtilities.o" "../../../target/compiledC/utils/GraphGenerator.o"
