mkdir "..\\..\\..\\target\\compiledC\\algorithms" "..\\..\\..\\target\\compiledC\\tests" "..\\..\\..\\target\\compiledC\\utils"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\algorithms\\BellmanFordParallelV1.o" ".\\algorithms\\BellmanFordParallelV1.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\algorithms\\BellmanFordSerial.o" ".\\algorithms\\BellmanFordSerial.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\algorithms\\DijkstraParallelV1.o" ".\\algorithms\\DijkstraParallelV1.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\algorithms\\DijkstraParallelV2.o" ".\\algorithms\\DijkstraParallelV2.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\algorithms\\DijkstraSerial.o" ".\\algorithms\\DijkstraSerial.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\tests\\Main.o" ".\\tests\\Main.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\tests\\TestBellmanFordSerial.o" ".\\tests\\TestBellmanFordSerial.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\tests\\TestDijkstraSerial.o" ".\\tests\\TestDijkstraSerial.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\tests\\TestGraphGenerator.o" ".\\tests\\TestGraphGenerator.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\utils\\ArraysUtilities.o" ".\\utils\\ArraysUtilities.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "..\\..\\..\\target\\compiledC\\utils\\GraphGenerator.o" ".\\utils\\GraphGenerator.c"
gcc -fopenmp -o "Shortest Path" "..\\..\\..\\target\\compiledC\\algorithms\\BellmanFordParallelV1.o" "..\\..\\..\\target\\compiledC\\algorithms\\BellmanFordSerial.o" "..\\..\\..\\target\\compiledC\\algorithms\\DijkstraParallelV1.o" "..\\..\\..\\target\\compiledC\\algorithms\\DijkstraParallelV2.o" "..\\..\\..\\target\\compiledC\\algorithms\\DijkstraSerial.o" "..\\..\\..\\target\\compiledC\\tests\\Main.o" "..\\..\\..\\target\\compiledC\\tests\\TestBellmanFordSerial.o" "..\\..\\..\\target\\compiledC\\tests\\TestDijkstraSerial.o" "..\\..\\..\\target\\compiledC\\tests\\TestGraphGenerator.o" "..\\..\\..\\target\\compiledC\\utils\\ArraysUtilities.o" "..\\..\\..\\target\\compiledC\\utils\\GraphGenerator.o"
