mkdir "../../../target/compiledC/tests"
mkdir "../../../target/compiledC/algorithms"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/tests/Main.o" "./tests/Main.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/algorithms/DijkstraSerial.o" "./algorithms/DijkstraSerial.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/algorithms/BellmanFordSerial.o" "./algorithms/BellmanFordSerial.c"
gcc -fopenmp -O3 -Wall -c -fmessage-length=0 -o "../../../target/compiledC/algorithms/Graph.o" "./algorithms/Graph.c"
gcc -fopenmp -o "Shortest Path" "../../../target/compiledC/tests/Main.o" "../../../target/compiledC/algorithms/DijkstraSerial.o" "../../../target/compiledC/algorithms/BellmanFordSerial.o" "../../../target/compiledC/algorithms/Graph.o"